[package]
name = "fortune"
version = "0.1.0"
description = "fortune is a program that displays a pseudorandom message from a database of quotations"
readme = "README.md"
repository = "https://github.com/wapm-packages/fortune"

[[module]]
name = "fortune"
source = "target/wasm32-unknown-wasi/release/fortune.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "fortune"
module = "fortune"
